### ISSUE TITLE
Enable super-admins to manage exhibits through the UI

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#1327]
This is a feature ticket encompassing several specific tickets that together will add functionality to the exhibits home page and enable super-admins to manage exhibits using the UI:

- [x] Add sidebar links to exhibits home - #1323
- [x] Add role-based filtering of the exhibits displayed on exhibits home - #1324
- [x] Enable super-admin to customize appearance of exhibits home - #1325
- [x] Enable super-admin to add and remove other super-admins - #849
- [x] Enable super-admin to reorder exhibits and view status details - #1326

**Comment by cbeer** [comment]
@jkeck this is :checkered_flag:, right?

**Comment by jkeck** [comment]
:+1:
